"""Interpretable, leakage-resistant MS2 same-compound shadow classifier."""

from .contracts import (
    ELIGIBLE_TRUTH_LABELS,
    FROZEN_CLOSE_PEAK_RULE,
    FROZEN_SOURCE_PARAMETERS,
    LEAKAGE_DENYLIST,
    ML_DIAGNOSTIC_STATUSES,
    ML_OUTPUT_FIELDS,
    TRUTH_LABELS,
    filter_labeled_rows,
    make_trainable_artifact,
    normalize_truth_label,
    truth_to_binary,
    validate_frozen_source,
    validate_no_leakage,
    validate_trainable_artifact,
    validate_truth_row,
)
from .features import (
    FEATURE_NAMES,
    SpectrumFeatures,
    extract_features,
    extract_features_from_row,
    feature_vector,
)
from .logistic import (
    C_GRID,
    CLASS_WEIGHT_GRID,
    L2LogisticModel,
    StandardScaler,
    fit_l2_logistic,
)
from .metrics import (
    BinaryMetrics,
    average_precision,
    binary_metrics,
    calibration_table,
    confusion_matrix,
    group_bootstrap_ci,
    pr_auc,
    select_threshold_for_specificity,
)
from .splits import (
    FoldSplit,
    GroupedExample,
    LockedBatchSplit,
    assert_group_isolation,
    build_leave_one_batch_out_folds,
    build_locked_batch_split,
    validate_binary_fold,
)

__all__ = [
    "CLASS_WEIGHT_GRID",
    "C_GRID",
    "ELIGIBLE_TRUTH_LABELS",
    "FEATURE_NAMES",
    "FROZEN_CLOSE_PEAK_RULE",
    "FROZEN_SOURCE_PARAMETERS",
    "LEAKAGE_DENYLIST",
    "ML_DIAGNOSTIC_STATUSES",
    "ML_OUTPUT_FIELDS",
    "TRUTH_LABELS",
    "BinaryMetrics",
    "FoldSplit",
    "GroupedExample",
    "L2LogisticModel",
    "LockedBatchSplit",
    "SpectrumFeatures",
    "StandardScaler",
    "assert_group_isolation",
    "average_precision",
    "binary_metrics",
    "build_leave_one_batch_out_folds",
    "build_locked_batch_split",
    "calibration_table",
    "confusion_matrix",
    "extract_features",
    "extract_features_from_row",
    "feature_vector",
    "filter_labeled_rows",
    "fit_l2_logistic",
    "group_bootstrap_ci",
    "make_trainable_artifact",
    "normalize_truth_label",
    "pr_auc",
    "select_threshold_for_specificity",
    "truth_to_binary",
    "validate_binary_fold",
    "validate_frozen_source",
    "validate_no_leakage",
    "validate_trainable_artifact",
    "validate_truth_row",
]
